// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDeviceLiveToolsPingReader is a Reader for the GetDeviceLiveToolsPing structure.
type GetDeviceLiveToolsPingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceLiveToolsPingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceLiveToolsPingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeviceLiveToolsPingOK creates a GetDeviceLiveToolsPingOK with default headers values
func NewGetDeviceLiveToolsPingOK() *GetDeviceLiveToolsPingOK {
	return &GetDeviceLiveToolsPingOK{}
}

/* GetDeviceLiveToolsPingOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetDeviceLiveToolsPingOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get device live tools ping o k response has a 2xx status code
func (o *GetDeviceLiveToolsPingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get device live tools ping o k response has a 3xx status code
func (o *GetDeviceLiveToolsPingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device live tools ping o k response has a 4xx status code
func (o *GetDeviceLiveToolsPingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get device live tools ping o k response has a 5xx status code
func (o *GetDeviceLiveToolsPingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get device live tools ping o k response a status code equal to that given
func (o *GetDeviceLiveToolsPingOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetDeviceLiveToolsPingOK) Error() string {
	return fmt.Sprintf("[GET /devices/{serial}/liveTools/ping/{id}][%d] getDeviceLiveToolsPingOK  %+v", 200, o.Payload)
}

func (o *GetDeviceLiveToolsPingOK) String() string {
	return fmt.Sprintf("[GET /devices/{serial}/liveTools/ping/{id}][%d] getDeviceLiveToolsPingOK  %+v", 200, o.Payload)
}

func (o *GetDeviceLiveToolsPingOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetDeviceLiveToolsPingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
