// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkWebhooksPayloadTemplatesReader is a Reader for the GetNetworkWebhooksPayloadTemplates structure.
type GetNetworkWebhooksPayloadTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkWebhooksPayloadTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkWebhooksPayloadTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetNetworkWebhooksPayloadTemplatesOK creates a GetNetworkWebhooksPayloadTemplatesOK with default headers values
func NewGetNetworkWebhooksPayloadTemplatesOK() *GetNetworkWebhooksPayloadTemplatesOK {
	return &GetNetworkWebhooksPayloadTemplatesOK{}
}

/* GetNetworkWebhooksPayloadTemplatesOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetNetworkWebhooksPayloadTemplatesOK struct {
	Payload []interface{}
}

// IsSuccess returns true when this get network webhooks payload templates o k response has a 2xx status code
func (o *GetNetworkWebhooksPayloadTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get network webhooks payload templates o k response has a 3xx status code
func (o *GetNetworkWebhooksPayloadTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network webhooks payload templates o k response has a 4xx status code
func (o *GetNetworkWebhooksPayloadTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get network webhooks payload templates o k response has a 5xx status code
func (o *GetNetworkWebhooksPayloadTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get network webhooks payload templates o k response a status code equal to that given
func (o *GetNetworkWebhooksPayloadTemplatesOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetNetworkWebhooksPayloadTemplatesOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/webhooks/payloadTemplates][%d] getNetworkWebhooksPayloadTemplatesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkWebhooksPayloadTemplatesOK) String() string {
	return fmt.Sprintf("[GET /networks/{networkId}/webhooks/payloadTemplates][%d] getNetworkWebhooksPayloadTemplatesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkWebhooksPayloadTemplatesOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetNetworkWebhooksPayloadTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
