// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkFirmwareUpgradesReader is a Reader for the GetNetworkFirmwareUpgrades structure.
type GetNetworkFirmwareUpgradesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkFirmwareUpgradesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkFirmwareUpgradesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetNetworkFirmwareUpgradesOK creates a GetNetworkFirmwareUpgradesOK with default headers values
func NewGetNetworkFirmwareUpgradesOK() *GetNetworkFirmwareUpgradesOK {
	return &GetNetworkFirmwareUpgradesOK{}
}

/* GetNetworkFirmwareUpgradesOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetNetworkFirmwareUpgradesOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get network firmware upgrades o k response has a 2xx status code
func (o *GetNetworkFirmwareUpgradesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get network firmware upgrades o k response has a 3xx status code
func (o *GetNetworkFirmwareUpgradesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network firmware upgrades o k response has a 4xx status code
func (o *GetNetworkFirmwareUpgradesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get network firmware upgrades o k response has a 5xx status code
func (o *GetNetworkFirmwareUpgradesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get network firmware upgrades o k response a status code equal to that given
func (o *GetNetworkFirmwareUpgradesOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetNetworkFirmwareUpgradesOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/firmwareUpgrades][%d] getNetworkFirmwareUpgradesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkFirmwareUpgradesOK) String() string {
	return fmt.Sprintf("[GET /networks/{networkId}/firmwareUpgrades][%d] getNetworkFirmwareUpgradesOK  %+v", 200, o.Payload)
}

func (o *GetNetworkFirmwareUpgradesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetNetworkFirmwareUpgradesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
