// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationDevicesStatusesOverviewReader is a Reader for the GetOrganizationDevicesStatusesOverview structure.
type GetOrganizationDevicesStatusesOverviewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationDevicesStatusesOverviewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationDevicesStatusesOverviewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationDevicesStatusesOverviewOK creates a GetOrganizationDevicesStatusesOverviewOK with default headers values
func NewGetOrganizationDevicesStatusesOverviewOK() *GetOrganizationDevicesStatusesOverviewOK {
	return &GetOrganizationDevicesStatusesOverviewOK{}
}

/* GetOrganizationDevicesStatusesOverviewOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetOrganizationDevicesStatusesOverviewOK struct {
	Payload interface{}
}

// IsSuccess returns true when this get organization devices statuses overview o k response has a 2xx status code
func (o *GetOrganizationDevicesStatusesOverviewOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization devices statuses overview o k response has a 3xx status code
func (o *GetOrganizationDevicesStatusesOverviewOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization devices statuses overview o k response has a 4xx status code
func (o *GetOrganizationDevicesStatusesOverviewOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization devices statuses overview o k response has a 5xx status code
func (o *GetOrganizationDevicesStatusesOverviewOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization devices statuses overview o k response a status code equal to that given
func (o *GetOrganizationDevicesStatusesOverviewOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetOrganizationDevicesStatusesOverviewOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/devices/statuses/overview][%d] getOrganizationDevicesStatusesOverviewOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationDevicesStatusesOverviewOK) String() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/devices/statuses/overview][%d] getOrganizationDevicesStatusesOverviewOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationDevicesStatusesOverviewOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationDevicesStatusesOverviewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
