// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationBrandingPoliciesReader is a Reader for the GetOrganizationBrandingPolicies structure.
type GetOrganizationBrandingPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationBrandingPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationBrandingPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationBrandingPoliciesOK creates a GetOrganizationBrandingPoliciesOK with default headers values
func NewGetOrganizationBrandingPoliciesOK() *GetOrganizationBrandingPoliciesOK {
	return &GetOrganizationBrandingPoliciesOK{}
}

/* GetOrganizationBrandingPoliciesOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetOrganizationBrandingPoliciesOK struct {
	Payload []interface{}
}

// IsSuccess returns true when this get organization branding policies o k response has a 2xx status code
func (o *GetOrganizationBrandingPoliciesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization branding policies o k response has a 3xx status code
func (o *GetOrganizationBrandingPoliciesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization branding policies o k response has a 4xx status code
func (o *GetOrganizationBrandingPoliciesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization branding policies o k response has a 5xx status code
func (o *GetOrganizationBrandingPoliciesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization branding policies o k response a status code equal to that given
func (o *GetOrganizationBrandingPoliciesOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetOrganizationBrandingPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/brandingPolicies][%d] getOrganizationBrandingPoliciesOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationBrandingPoliciesOK) String() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/brandingPolicies][%d] getOrganizationBrandingPoliciesOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationBrandingPoliciesOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetOrganizationBrandingPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
