// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNetworkApplianceRfProfileParams creates a new GetNetworkApplianceRfProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNetworkApplianceRfProfileParams() *GetNetworkApplianceRfProfileParams {
	return &GetNetworkApplianceRfProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNetworkApplianceRfProfileParamsWithTimeout creates a new GetNetworkApplianceRfProfileParams object
// with the ability to set a timeout on a request.
func NewGetNetworkApplianceRfProfileParamsWithTimeout(timeout time.Duration) *GetNetworkApplianceRfProfileParams {
	return &GetNetworkApplianceRfProfileParams{
		timeout: timeout,
	}
}

// NewGetNetworkApplianceRfProfileParamsWithContext creates a new GetNetworkApplianceRfProfileParams object
// with the ability to set a context for a request.
func NewGetNetworkApplianceRfProfileParamsWithContext(ctx context.Context) *GetNetworkApplianceRfProfileParams {
	return &GetNetworkApplianceRfProfileParams{
		Context: ctx,
	}
}

// NewGetNetworkApplianceRfProfileParamsWithHTTPClient creates a new GetNetworkApplianceRfProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNetworkApplianceRfProfileParamsWithHTTPClient(client *http.Client) *GetNetworkApplianceRfProfileParams {
	return &GetNetworkApplianceRfProfileParams{
		HTTPClient: client,
	}
}

/*
GetNetworkApplianceRfProfileParams contains all the parameters to send to the API endpoint

	for the get network appliance rf profile operation.

	Typically these are written to a http.Request.
*/
type GetNetworkApplianceRfProfileParams struct {

	/* NetworkID.

	   Network ID
	*/
	NetworkID string

	/* RfProfileID.

	   Rf profile ID
	*/
	RfProfileID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get network appliance rf profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkApplianceRfProfileParams) WithDefaults() *GetNetworkApplianceRfProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get network appliance rf profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNetworkApplianceRfProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) WithTimeout(timeout time.Duration) *GetNetworkApplianceRfProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) WithContext(ctx context.Context) *GetNetworkApplianceRfProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) WithHTTPClient(client *http.Client) *GetNetworkApplianceRfProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkID adds the networkID to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) WithNetworkID(networkID string) *GetNetworkApplianceRfProfileParams {
	o.SetNetworkID(networkID)
	return o
}

// SetNetworkID adds the networkId to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) SetNetworkID(networkID string) {
	o.NetworkID = networkID
}

// WithRfProfileID adds the rfProfileID to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) WithRfProfileID(rfProfileID string) *GetNetworkApplianceRfProfileParams {
	o.SetRfProfileID(rfProfileID)
	return o
}

// SetRfProfileID adds the rfProfileId to the get network appliance rf profile params
func (o *GetNetworkApplianceRfProfileParams) SetRfProfileID(rfProfileID string) {
	o.RfProfileID = rfProfileID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNetworkApplianceRfProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param networkId
	if err := r.SetPathParam("networkId", o.NetworkID); err != nil {
		return err
	}

	// path param rfProfileId
	if err := r.SetPathParam("rfProfileId", o.RfProfileID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
