// Code generated by go-swagger; DO NOT EDIT.

package appliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateDeviceApplianceRadioSettingsParams creates a new UpdateDeviceApplianceRadioSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateDeviceApplianceRadioSettingsParams() *UpdateDeviceApplianceRadioSettingsParams {
	return &UpdateDeviceApplianceRadioSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDeviceApplianceRadioSettingsParamsWithTimeout creates a new UpdateDeviceApplianceRadioSettingsParams object
// with the ability to set a timeout on a request.
func NewUpdateDeviceApplianceRadioSettingsParamsWithTimeout(timeout time.Duration) *UpdateDeviceApplianceRadioSettingsParams {
	return &UpdateDeviceApplianceRadioSettingsParams{
		timeout: timeout,
	}
}

// NewUpdateDeviceApplianceRadioSettingsParamsWithContext creates a new UpdateDeviceApplianceRadioSettingsParams object
// with the ability to set a context for a request.
func NewUpdateDeviceApplianceRadioSettingsParamsWithContext(ctx context.Context) *UpdateDeviceApplianceRadioSettingsParams {
	return &UpdateDeviceApplianceRadioSettingsParams{
		Context: ctx,
	}
}

// NewUpdateDeviceApplianceRadioSettingsParamsWithHTTPClient creates a new UpdateDeviceApplianceRadioSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateDeviceApplianceRadioSettingsParamsWithHTTPClient(client *http.Client) *UpdateDeviceApplianceRadioSettingsParams {
	return &UpdateDeviceApplianceRadioSettingsParams{
		HTTPClient: client,
	}
}

/*
UpdateDeviceApplianceRadioSettingsParams contains all the parameters to send to the API endpoint

	for the update device appliance radio settings operation.

	Typically these are written to a http.Request.
*/
type UpdateDeviceApplianceRadioSettingsParams struct {

	/* Serial.

	   Serial
	*/
	Serial string

	// UpdateDeviceApplianceRadioSettings.
	UpdateDeviceApplianceRadioSettings UpdateDeviceApplianceRadioSettingsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update device appliance radio settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDeviceApplianceRadioSettingsParams) WithDefaults() *UpdateDeviceApplianceRadioSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update device appliance radio settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateDeviceApplianceRadioSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) WithTimeout(timeout time.Duration) *UpdateDeviceApplianceRadioSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) WithContext(ctx context.Context) *UpdateDeviceApplianceRadioSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) WithHTTPClient(client *http.Client) *UpdateDeviceApplianceRadioSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSerial adds the serial to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) WithSerial(serial string) *UpdateDeviceApplianceRadioSettingsParams {
	o.SetSerial(serial)
	return o
}

// SetSerial adds the serial to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) SetSerial(serial string) {
	o.Serial = serial
}

// WithUpdateDeviceApplianceRadioSettings adds the updateDeviceApplianceRadioSettings to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) WithUpdateDeviceApplianceRadioSettings(updateDeviceApplianceRadioSettings UpdateDeviceApplianceRadioSettingsBody) *UpdateDeviceApplianceRadioSettingsParams {
	o.SetUpdateDeviceApplianceRadioSettings(updateDeviceApplianceRadioSettings)
	return o
}

// SetUpdateDeviceApplianceRadioSettings adds the updateDeviceApplianceRadioSettings to the update device appliance radio settings params
func (o *UpdateDeviceApplianceRadioSettingsParams) SetUpdateDeviceApplianceRadioSettings(updateDeviceApplianceRadioSettings UpdateDeviceApplianceRadioSettingsBody) {
	o.UpdateDeviceApplianceRadioSettings = updateDeviceApplianceRadioSettings
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDeviceApplianceRadioSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param serial
	if err := r.SetPathParam("serial", o.Serial); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.UpdateDeviceApplianceRadioSettings); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
