// Code generated by go-swagger; DO NOT EDIT.

package switch_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetOrganizationSwitchPortsBySwitchReader is a Reader for the GetOrganizationSwitchPortsBySwitch structure.
type GetOrganizationSwitchPortsBySwitchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationSwitchPortsBySwitchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationSwitchPortsBySwitchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationSwitchPortsBySwitchOK creates a GetOrganizationSwitchPortsBySwitchOK with default headers values
func NewGetOrganizationSwitchPortsBySwitchOK() *GetOrganizationSwitchPortsBySwitchOK {
	return &GetOrganizationSwitchPortsBySwitchOK{}
}

/* GetOrganizationSwitchPortsBySwitchOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetOrganizationSwitchPortsBySwitchOK struct {

	/* A comma-separated list of first, last, prev, and next relative links used for subsequent paginated requests.
	 */
	Link string

	Payload interface{}
}

// IsSuccess returns true when this get organization switch ports by switch o k response has a 2xx status code
func (o *GetOrganizationSwitchPortsBySwitchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get organization switch ports by switch o k response has a 3xx status code
func (o *GetOrganizationSwitchPortsBySwitchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get organization switch ports by switch o k response has a 4xx status code
func (o *GetOrganizationSwitchPortsBySwitchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get organization switch ports by switch o k response has a 5xx status code
func (o *GetOrganizationSwitchPortsBySwitchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get organization switch ports by switch o k response a status code equal to that given
func (o *GetOrganizationSwitchPortsBySwitchOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetOrganizationSwitchPortsBySwitchOK) Error() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/switch/ports/bySwitch][%d] getOrganizationSwitchPortsBySwitchOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationSwitchPortsBySwitchOK) String() string {
	return fmt.Sprintf("[GET /organizations/{organizationId}/switch/ports/bySwitch][%d] getOrganizationSwitchPortsBySwitchOK  %+v", 200, o.Payload)
}

func (o *GetOrganizationSwitchPortsBySwitchOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetOrganizationSwitchPortsBySwitchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Link
	hdrLink := response.GetHeader("Link")

	if hdrLink != "" {
		o.Link = hdrLink
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
