// Code generated by go-swagger; DO NOT EDIT.

package switch_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetDeviceSwitchPortsReader is a Reader for the GetDeviceSwitchPorts structure.
type GetDeviceSwitchPortsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeviceSwitchPortsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeviceSwitchPortsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeviceSwitchPortsOK creates a GetDeviceSwitchPortsOK with default headers values
func NewGetDeviceSwitchPortsOK() *GetDeviceSwitchPortsOK {
	return &GetDeviceSwitchPortsOK{}
}

/* GetDeviceSwitchPortsOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetDeviceSwitchPortsOK struct {
	Payload []interface{}
}

// IsSuccess returns true when this get device switch ports o k response has a 2xx status code
func (o *GetDeviceSwitchPortsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get device switch ports o k response has a 3xx status code
func (o *GetDeviceSwitchPortsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get device switch ports o k response has a 4xx status code
func (o *GetDeviceSwitchPortsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get device switch ports o k response has a 5xx status code
func (o *GetDeviceSwitchPortsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get device switch ports o k response a status code equal to that given
func (o *GetDeviceSwitchPortsOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetDeviceSwitchPortsOK) Error() string {
	return fmt.Sprintf("[GET /devices/{serial}/switch/ports][%d] getDeviceSwitchPortsOK  %+v", 200, o.Payload)
}

func (o *GetDeviceSwitchPortsOK) String() string {
	return fmt.Sprintf("[GET /devices/{serial}/switch/ports][%d] getDeviceSwitchPortsOK  %+v", 200, o.Payload)
}

func (o *GetDeviceSwitchPortsOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetDeviceSwitchPortsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
