// Code generated by go-swagger; DO NOT EDIT.

package wireless

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetNetworkWirelessSsidIdentityPsksReader is a Reader for the GetNetworkWirelessSsidIdentityPsks structure.
type GetNetworkWirelessSsidIdentityPsksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNetworkWirelessSsidIdentityPsksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetNetworkWirelessSsidIdentityPsksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetNetworkWirelessSsidIdentityPsksOK creates a GetNetworkWirelessSsidIdentityPsksOK with default headers values
func NewGetNetworkWirelessSsidIdentityPsksOK() *GetNetworkWirelessSsidIdentityPsksOK {
	return &GetNetworkWirelessSsidIdentityPsksOK{}
}

/* GetNetworkWirelessSsidIdentityPsksOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetNetworkWirelessSsidIdentityPsksOK struct {
	Payload []interface{}
}

// IsSuccess returns true when this get network wireless ssid identity psks o k response has a 2xx status code
func (o *GetNetworkWirelessSsidIdentityPsksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get network wireless ssid identity psks o k response has a 3xx status code
func (o *GetNetworkWirelessSsidIdentityPsksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get network wireless ssid identity psks o k response has a 4xx status code
func (o *GetNetworkWirelessSsidIdentityPsksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get network wireless ssid identity psks o k response has a 5xx status code
func (o *GetNetworkWirelessSsidIdentityPsksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get network wireless ssid identity psks o k response a status code equal to that given
func (o *GetNetworkWirelessSsidIdentityPsksOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetNetworkWirelessSsidIdentityPsksOK) Error() string {
	return fmt.Sprintf("[GET /networks/{networkId}/wireless/ssids/{number}/identityPsks][%d] getNetworkWirelessSsidIdentityPsksOK  %+v", 200, o.Payload)
}

func (o *GetNetworkWirelessSsidIdentityPsksOK) String() string {
	return fmt.Sprintf("[GET /networks/{networkId}/wireless/ssids/{number}/identityPsks][%d] getNetworkWirelessSsidIdentityPsksOK  %+v", 200, o.Payload)
}

func (o *GetNetworkWirelessSsidIdentityPsksOK) GetPayload() []interface{} {
	return o.Payload
}

func (o *GetNetworkWirelessSsidIdentityPsksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
